upstream gunicorn_edonius {
    server 127.0.0.1:8013;
}

# HTTP → HTTPS redirect
server {
    listen 80;
    server_name edonius.hs-dev.cz;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

# HTTPS
server {
    listen 443 ssl;
    server_name edonius.hs-dev.cz;

    ssl_certificate /etc/letsencrypt/live/edonius.hs-dev.cz/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/edonius.hs-dev.cz/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    location /static/ {
        alias /srv/apps/13_Edonius/staticfiles/;
    }

    location / {
        include proxy_params;
        proxy_pass http://gunicorn_edonius;
    }
}
