# Generated by Django 4.2.30 on 2026-05-28 21:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=7, unique=True, validators=[django.core.validators.RegexValidator(message='Použij formát RRRR/YY, např. 2025/26.', regex='^\\d{4}/\\d{2}$')])),
            ],
            options={
                'verbose_name': 'Školní rok',
                'verbose_name_plural': 'Školní roky',
                'ordering': ['-name'],
            },
        ),
    ]
