# Generated by Django 4.2.30 on 2026-05-28 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Kód předmětu')),
                ('name', models.CharField(max_length=120, verbose_name='Název předmětu')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktivní')),
            ],
            options={
                'verbose_name': 'Předmět',
                'verbose_name_plural': 'Předměty',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SubjectInSchoolYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Název v daném školním roce')),
                ('abbreviation', models.CharField(blank=True, max_length=20, verbose_name='Zkratka')),
                ('is_taught', models.BooleanField(default=True, verbose_name='Vyučovaný')),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subject_entries', to='core.schoolyear', verbose_name='Školní rok')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='school_year_entries', to='core.subject', verbose_name='Předmět')),
            ],
            options={
                'verbose_name': 'Předmět ve školním roce',
                'verbose_name_plural': 'Předměty ve školních rocích',
                'ordering': ['-school_year__name', 'name'],
            },
        ),
        migrations.AddConstraint(
            model_name='subjectinschoolyear',
            constraint=models.UniqueConstraint(fields=('subject', 'school_year'), name='unique_subject_per_school_year'),
        ),
    ]
