# Generated by Django 4.2.30 on 2026-05-28 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_subject_subjectinschoolyear_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subjectinschoolyear',
            options={'ordering': ['-school_year__name', 'name'], 'verbose_name': 'Předmět ve školním roce', 'verbose_name_plural': 'Předměty ve školním roce'},
        ),
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Název třídy')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktivní')),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classes', to='core.schoolyear', verbose_name='Školní rok')),
            ],
            options={
                'verbose_name': 'Třída',
                'verbose_name_plural': 'Třídy',
                'ordering': ['-school_year__name', 'name'],
            },
        ),
        migrations.AddConstraint(
            model_name='schoolclass',
            constraint=models.UniqueConstraint(fields=('school_year', 'name'), name='unique_class_name_per_school_year'),
        ),
    ]
