# Generated by Django 4.2.30 on 2026-05-28 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_subjectinschoolyear_options_schoolclass_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectClassInSchoolYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktivní')),
                ('predmet_ve_skolnim_roce', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tridni_vazby', to='core.subjectinschoolyear', verbose_name='Předmět ve školním roce')),
                ('trida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='predmetove_vazby', to='core.schoolclass', verbose_name='Třída')),
            ],
            options={
                'verbose_name': 'Předmět a třída ve školním roce',
                'verbose_name_plural': 'Předměty a třídy ve školním roce',
                'ordering': ['-predmet_ve_skolnim_roce__school_year__name', 'trida__name', 'predmet_ve_skolnim_roce__name'],
            },
        ),
        migrations.AddConstraint(
            model_name='subjectclassinschoolyear',
            constraint=models.UniqueConstraint(fields=('predmet_ve_skolnim_roce', 'trida'), name='unique_subject_class_in_school_year'),
        ),
    ]
