# Generated by Django 4.2.30 on 2026-05-28 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_subjectclassinschoolyear_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cislo_oboru', models.CharField(max_length=30, unique=True, verbose_name='Číslo oboru')),
                ('zkratka', models.CharField(max_length=20, unique=True, verbose_name='Zkratka')),
                ('nazev', models.CharField(max_length=150, verbose_name='Název oboru vzdělávání')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktivní')),
            ],
            options={
                'verbose_name': 'Obor vzdělávání',
                'verbose_name_plural': 'Obory vzdělávání',
                'ordering': ['nazev'],
            },
        ),
        migrations.AlterModelOptions(
            name='subjectclassinschoolyear',
            options={'ordering': ['-predmet_ve_skolnim_roce__school_year__name', 'trida__name', 'predmet_ve_skolnim_roce__name'], 'verbose_name': 'Předměty tříd ve školním roce', 'verbose_name_plural': 'Předměty tříd ve školním roce'},
        ),
        migrations.CreateModel(
            name='StudyFieldInSchoolYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=150, verbose_name='Název v daném školním roce')),
                ('zkratka', models.CharField(max_length=20, verbose_name='Zkratka v daném školním roce')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktivní')),
                ('obor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='school_year_entries', to='core.studyfield', verbose_name='Obor vzdělávání')),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='study_field_entries', to='core.schoolyear', verbose_name='Školní rok')),
            ],
            options={
                'verbose_name': 'Obor vzdělávání ve školním roce',
                'verbose_name_plural': 'Obory vzdělávání ve školním roce',
                'ordering': ['-school_year__name', 'nazev'],
            },
        ),
        migrations.AddConstraint(
            model_name='studyfieldinschoolyear',
            constraint=models.UniqueConstraint(fields=('obor', 'school_year'), name='unique_study_field_per_school_year'),
        ),
        migrations.AddConstraint(
            model_name='studyfieldinschoolyear',
            constraint=models.UniqueConstraint(fields=('school_year', 'zkratka'), name='unique_study_field_abbreviation_per_school_year'),
        ),
    ]
