# Generated by Django 4.2.30 on 2026-05-29 07:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_studyfield_alter_subjectclassinschoolyear_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeachingGroupInSchoolYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Název skupiny')),
                ('code', models.CharField(blank=True, max_length=30, verbose_name='Kód skupiny')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktivní')),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teaching_groups', to='core.schoolyear', verbose_name='Školní rok')),
            ],
            options={
                'verbose_name': 'Skupina ve školním roce',
                'verbose_name_plural': 'Skupiny ve školním roce',
                'ordering': ['-school_year__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TeacherAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktivní')),
                ('group_in_school_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='teacher_assignments', to='core.teachinggroupinschoolyear', verbose_name='Skupina ve školním roce')),
                ('subject_class_in_school_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teacher_assignments', to='core.subjectclassinschoolyear', verbose_name='Předmět a třída ve školním roce')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teaching_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Učitel')),
            ],
            options={
                'verbose_name': 'Úvazek učitele',
                'verbose_name_plural': 'Úvazky učitelů',
                'ordering': ['-subject_class_in_school_year__predmet_ve_skolnim_roce__school_year__name', 'teacher__last_name', 'teacher__first_name'],
            },
        ),
        migrations.AddConstraint(
            model_name='teachinggroupinschoolyear',
            constraint=models.UniqueConstraint(fields=('school_year', 'name'), name='unique_teaching_group_name_per_school_year'),
        ),
        migrations.AddConstraint(
            model_name='teacherassignment',
            constraint=models.UniqueConstraint(fields=('teacher', 'subject_class_in_school_year', 'group_in_school_year'), name='unique_teacher_assignment_per_scope'),
        ),
    ]
