# Generated by Django 4.2.30 on 2026-05-29 08:01

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_teachinggroupinschoolyear_teacherassignment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortcut', models.CharField(max_length=8, unique=True, validators=[django.core.validators.RegexValidator(message='Zkratka může obsahovat jen písmena/čísla (1-8 znaků).', regex='^[A-Za-z0-9]{1,8}$')], verbose_name='Zkratka učitele')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktivní')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL, verbose_name='Uživatel')),
            ],
            options={
                'verbose_name': 'Učitel',
                'verbose_name_plural': 'Učitelé',
                'ordering': ['shortcut'],
            },
        ),
    ]
