# Generated by Django 4.2.30 on 2026-05-28 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_alter_subjectinschoolyear_options_schoolclass_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TematickyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=150, verbose_name='Název tematického plánu')),
                ('popis', models.TextField(blank=True, verbose_name='Popis')),
                ('is_aktivni', models.BooleanField(default=True, verbose_name='Aktivní')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vytvořeno')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Upraveno')),
                ('predmet_ve_skolnim_roce', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tematicke_plany', to='core.subjectinschoolyear', verbose_name='Předmět ve školním roce')),
                ('trida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tematicke_plany', to='core.schoolclass', verbose_name='Třída')),
            ],
            options={
                'verbose_name': 'Tematický plán',
                'verbose_name_plural': 'Tematické plány',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='tematickyplan',
            constraint=models.UniqueConstraint(fields=('predmet_ve_skolnim_roce', 'trida', 'nazev'), name='unique_plan_name_per_subject_class_in_school_year'),
        ),
    ]
