# Generated by Django 4.2.30 on 2026-05-28 22:15

from django.db import migrations, models
import django.db.models.deletion


def forward_fill_subject_class_link(apps, schema_editor):
    TematickyPlan = apps.get_model('temataky', 'TematickyPlan')
    SubjectClassInSchoolYear = apps.get_model('core', 'SubjectClassInSchoolYear')

    for plan in TematickyPlan.objects.all().iterator():
        subject_class_link, _ = SubjectClassInSchoolYear.objects.get_or_create(
            predmet_ve_skolnim_roce_id=plan.predmet_ve_skolnim_roce_id,
            trida_id=plan.trida_id,
            defaults={'is_active': True},
        )
        plan.predmet_trida_ve_skolnim_roce_id = subject_class_link.id
        plan.save(update_fields=['predmet_trida_ve_skolnim_roce'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_subjectclassinschoolyear_and_more'),
        ('temataky', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tematickyplan',
            name='unique_plan_name_per_subject_class_in_school_year',
        ),
        migrations.AddField(
            model_name='tematickyplan',
            name='predmet_trida_ve_skolnim_roce',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tematicke_plany', to='core.subjectclassinschoolyear', verbose_name='Předmět a třída ve školním roce'),
        ),
        migrations.RunPython(forward_fill_subject_class_link, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='tematickyplan',
            name='predmet_trida_ve_skolnim_roce',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tematicke_plany', to='core.subjectclassinschoolyear', verbose_name='Předmět a třída ve školním roce'),
        ),
        migrations.RemoveField(
            model_name='tematickyplan',
            name='predmet_ve_skolnim_roce',
        ),
        migrations.RemoveField(
            model_name='tematickyplan',
            name='trida',
        ),
        migrations.AddConstraint(
            model_name='tematickyplan',
            constraint=models.UniqueConstraint(fields=('predmet_trida_ve_skolnim_roce', 'nazev'), name='unique_plan_name_per_subject_class_link_in_school_year'),
        ),
    ]
