# Generated by Django 4.2.30 on 2026-05-28 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('temataky', '0003_refactor_plan_to_multi_class_and_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='TematickeTema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poradi', models.PositiveSmallIntegerField(verbose_name='Pořadí')),
                ('nazev', models.CharField(max_length=150, verbose_name='Název tématu')),
                ('hodiny', models.PositiveSmallIntegerField(verbose_name='Počet hodin')),
                ('tematicky_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temata', to='temataky.tematickyplan', verbose_name='Tematický plán')),
            ],
            options={
                'verbose_name': 'Téma tematického plánu',
                'verbose_name_plural': 'Témata tematického plánu',
                'ordering': ['poradi', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TemaBod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poradi', models.PositiveSmallIntegerField(verbose_name='Pořadí')),
                ('nazev', models.CharField(max_length=200, verbose_name='Název bodu')),
                ('hodiny', models.PositiveSmallIntegerField(verbose_name='Počet hodin')),
                ('tema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='body', to='temataky.tematicketema', verbose_name='Téma')),
            ],
            options={
                'verbose_name': 'Bod tématu',
                'verbose_name_plural': 'Body tématu',
                'ordering': ['poradi', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='tematicketema',
            constraint=models.UniqueConstraint(fields=('tematicky_plan', 'poradi'), name='unique_tema_poradi_per_plan'),
        ),
        migrations.AddConstraint(
            model_name='temabod',
            constraint=models.UniqueConstraint(fields=('tema', 'poradi'), name='unique_bod_poradi_per_tema'),
        ),
    ]
