# Generated by Django 4.2.30 on 2026-05-28 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_studyfield_alter_subjectclassinschoolyear_options_and_more'),
        ('temataky', '0004_tematicketema_temabod_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tematickyplan',
            name='unique_plan_name_per_subject_in_school_year',
        ),
        migrations.AddField(
            model_name='tematickyplan',
            name='obor_ve_skolnim_roce',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tematicke_plany', to='core.studyfieldinschoolyear', verbose_name='Obor ve školním roce'),
        ),
        migrations.AddConstraint(
            model_name='tematickyplan',
            constraint=models.UniqueConstraint(fields=('obor_ve_skolnim_roce', 'predmet_ve_skolnim_roce', 'nazev'), name='unique_plan_name_per_field_subject_in_school_year'),
        ),
    ]
